services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${STORAGE_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_ROOT_PASS}
    volumes:
      - ./storage:/data
    command: ["server", "/data", "--address", ":${MINIO_API_PORT}", "--console-address", ":${MINIO_CONSOLE_PORT}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_API_PORT}/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

  # Changes video storage to be public read
  minio-setup:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:${MINIO_API_PORT} ${STORAGE_ROOT_USER} ${STORAGE_ROOT_PASS}) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing myminio/videos;
      /usr/bin/mc anonymous set download myminio/videos;
      exit 0;
      "

  postgres:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${MESSAGE_PORT}:5672"
      - "${WEBUI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis-backend:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  core-server:
    build:
      context: ./core
      dockerfile: Dockerfile
    volumes:
      - ./shared:/app/shared
    ports:
      - "${APP_PORT}:5000"
    environment:
      PYTHONPATH: /app
      MINIO_ENDPOINT: minio:${MINIO_API_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_HOST: ${RABBITMQ_HOST}
      MINIO_ROOT_USER: ${STORAGE_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_ROOT_PASS}
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
          condition: service_healthy
      minio:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
      redis-backend:
          condition: service_healthy

  video-worker:
    build:
      context: ./workers/video
      dockerfile: Dockerfile
    volumes:
      - ./shared:/app/shared
    environment:
      PYTHONPATH: /app
      MINIO_ENDPOINT: minio:${MINIO_API_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_HOST: ${RABBITMQ_HOST}
      MINIO_ROOT_USER: ${STORAGE_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_ROOT_PASS}
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
          condition: service_healthy
      minio:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
      redis-backend:
          condition: service_healthy

  client:
    build: client
    ports:
      - 3000:3000

  edge-node-1:
    image: nginx:alpine
    volumes:
      - ./edge/nginx/edge.conf:/etc/nginx/conf.d/default.conf:ro
      - edge1_cache:/var/cache/nginx
    environment:
      MINIO_ENDPOINT: "minio:${MINIO_API_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  edge-node-2:
    image: nginx:alpine
    volumes:
      - ./edge/nginx/edge.conf:/etc/nginx/conf.d/default.conf:ro
      - edge2_cache:/var/cache/nginx
    environment:
      MINIO_ENDPOINT: "minio:${MINIO_API_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  load-balancer:
    image: nginx:alpine
    volumes:
      - ./edge/nginx/lb.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - edge-node-1
      - edge-node-2

volumes:
  edge1_cache:
  edge2_cache: