
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    
    # MP4-video streaming
    location ~* \.(mp4|webm|ogg)$ {
        root /usr/share/nginx/html;
        add_header Content-Type video/mp4;
        add_header Accept-Ranges bytes;
        # force the browser to play instead of download
        add_header Content-Disposition "inline";
    }
}