upstream cdn_nodes {
    server edge_node_1:80;
    server edge_node_2:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://cdn_nodes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}